// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteDocumentData, DeleteDocumentErrors, DeleteDocumentResponses, DownloadDocumentData, DownloadDocumentErrors, DownloadDocumentResponses, GetDocumentChunkData, GetDocumentChunkErrors, GetDocumentChunkResponses, GetDocumentData, GetDocumentErrors, GetDocumentResponses, HealthAppData, HealthAppResponses, HealthCosData, HealthCosResponses, HealthDbData, HealthDbResponses, ListDocumentChunksData, ListDocumentChunksErrors, ListDocumentChunksResponses, ListDocumentsData, ListDocumentsErrors, ListDocumentsResponses, RetryDocumentData, RetryDocumentErrors, RetryDocumentResponses, UploadDocumentData, UploadDocumentErrors, UploadDocumentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const healthApp = <ThrowOnError extends boolean = false>(options?: Options<HealthAppData, ThrowOnError>) => (options?.client ?? client).get<HealthAppResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Health Db
 */
export const healthDb = <ThrowOnError extends boolean = false>(options?: Options<HealthDbData, ThrowOnError>) => (options?.client ?? client).get<HealthDbResponses, unknown, ThrowOnError>({ url: '/api/health/db', ...options });

/**
 * Health Cos
 */
export const healthCos = <ThrowOnError extends boolean = false>(options?: Options<HealthCosData, ThrowOnError>) => (options?.client ?? client).get<HealthCosResponses, unknown, ThrowOnError>({ url: '/api/health/cos', ...options });

/**
 * List Documents
 */
export const listDocuments = <ThrowOnError extends boolean = false>(options?: Options<ListDocumentsData, ThrowOnError>) => (options?.client ?? client).get<ListDocumentsResponses, ListDocumentsErrors, ThrowOnError>({ url: '/api/documents', ...options });

/**
 * Upload Document
 *
 * 上传文档：写入 COS、落库后立即返回，解析与向量化通过 BackgroundTasks 异步进行。
 */
export const uploadDocument = <ThrowOnError extends boolean = false>(options: Options<UploadDocumentData, ThrowOnError>) => (options.client ?? client).post<UploadDocumentResponses, UploadDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/documents',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete Document
 */
export const deleteDocument = <ThrowOnError extends boolean = false>(options: Options<DeleteDocumentData, ThrowOnError>) => (options.client ?? client).delete<DeleteDocumentResponses, DeleteDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}', ...options });

/**
 * Get Document
 */
export const getDocument = <ThrowOnError extends boolean = false>(options: Options<GetDocumentData, ThrowOnError>) => (options.client ?? client).get<GetDocumentResponses, GetDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}', ...options });

/**
 * Retry Document
 */
export const retryDocument = <ThrowOnError extends boolean = false>(options: Options<RetryDocumentData, ThrowOnError>) => (options.client ?? client).post<RetryDocumentResponses, RetryDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}/retry', ...options });

/**
 * Download Document
 *
 * 返回文档原始字节。
 *
 * - PDF / HTML / Markdown: 可在浏览器内联预览
 * - DOCX: 浏览器无法渲染, 强制 attachment
 */
export const downloadDocument = <ThrowOnError extends boolean = false>(options: Options<DownloadDocumentData, ThrowOnError>) => (options.client ?? client).get<DownloadDocumentResponses, DownloadDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}/file', ...options });

/**
 * List Document Chunks
 */
export const listDocumentChunks = <ThrowOnError extends boolean = false>(options: Options<ListDocumentChunksData, ThrowOnError>) => (options.client ?? client).get<ListDocumentChunksResponses, ListDocumentChunksErrors, ThrowOnError>({ url: '/api/documents/{document_id}/chunks', ...options });

/**
 * Get Document Chunk
 */
export const getDocumentChunk = <ThrowOnError extends boolean = false>(options: Options<GetDocumentChunkData, ThrowOnError>) => (options.client ?? client).get<GetDocumentChunkResponses, GetDocumentChunkErrors, ThrowOnError>({ url: '/api/documents/{document_id}/chunks/{chunk_id}', ...options });
